Repository Pujo-Atlas-Kolkata/PujoAtlasKol-Web, pull requests merged in 2024-10, with the labels that each got.

#143 fix: Teams Page UI & Content
  src/components/Members/TeamMembers.astro
  src/components/Members/index.tsx
  src/components/shared/Navbar.tsx
  src/constants/team.ts
  src/pages/bn/team.astro
  src/pages/team.astro
Labels: enhancement

#126 feat: changed social links to brand logos
  src/components/shared/Footer.astro
Labels: enhancement

#144 feat: pre-launch tweaks
  README.md
  src/components/Members/TeamMembers.astro
  src/components/app/home/Cards/PandalCard.tsx
  src/components/app/map/LocationMarker.tsx
  src/components/app/shared/Search/input.tsx
  src/constants/socials.ts
  src/constants/team.ts
  src/hooks/pandals/useAllPandals.ts
  src/hooks/pandals/useTrendingPandals.ts
  src/layouts/LandingPageLayout.astro
  src/layouts/WebAppLayout.astro
  src/pages/404.astro
  src/pages/app/help.astro
  src/pages/app/index.astro
  src/pages/app/pandals.astro
  src/pages/bn/index.astro
  src/pages/bn/team.astro
  src/pages/index.astro
  src/pages/team.astro
  src/stores/index.ts
  src/stores/pujo/index.ts
Labels: enhancement

#153 fix: auto snap location
  public/pandal-map-marker.svg
  src/components/app/map/LocationMarker.tsx
  src/components/app/map/UserLocation.tsx
Labels: bug

#160 feat: post-launch user feedback tweaks
  .env.example
  astro.config.mjs
  package-lock.json
  package.json
  src/components/Carousel/Cards.tsx
  src/constants/socials.ts
  src/pages/app/help.astro
Labels: enhancement

#162 feat: enhance marker info window
  src/components/app/home/Cards/Cards.tsx
  src/components/app/home/Cards/PandalCard.tsx
  src/components/app/map/ClusterMarker.tsx
  src/components/app/map/GoogleMap.tsx
  src/components/app/map/LocationMarker.tsx
  src/components/app/map/types.ts
  src/components/app/shared/AppHeader.astro
  src/pages/app/pandals.astro
Labels: enhancement

#165 fix: trending cards on landing should not be clickable on desktop sizes
  src/components/Carousel/Cards.tsx
Labels: bug

#169 feat: to create two buttons in the drawer container, showing status if the user has accepted or rejected location permission with toast
  .astro/settings.json
  package-lock.json
  package.json
  src/components/Carousel/Cards.tsx
  src/components/app/home/Cards/Cards.tsx
  src/components/app/shared/SettingsFlyout.tsx
Labels: enhancement

#172 fix: sentry collecting data from non-prod & non-staging environments
  .env.example
  astro.config.mjs
Labels: bug

#173 feat: in "Home" tab, for each pandal card - show its nearest metro station
  src/components/app/home/Cards/Cards.tsx
  src/components/app/home/Cards/PandalCard.tsx
  src/types/pujo.ts
Labels: enhancement

#174 feat: add metro info to pandal marker info box
  src/components/app/map/ClusterMarker.tsx
  src/components/app/map/LocationMarker.tsx
  src/components/app/map/types.ts
Labels: enhancement

#175 feat: add more info about location perms
  src/components/app/home/Cards/Cards.tsx
  src/components/app/shared/SettingsFlyout.tsx
Labels: enhancement

#167 feat: added OG tags
  src/layouts/LandingPageLayout.astro
  src/layouts/WebAppLayout.astro
Labels: enhancement

#177 chore: v1.1 tweaks
  package-lock.json
  package.json
  public/open-graph/bn.png
  public/open-graph/en.png
  src/layouts/LandingPageLayout.astro
  src/layouts/WebAppLayout.astro
Labels: enhancement

#179 fix!: Make only the search bar sticky, allowing "Near Me" and "Trending" buttons to scroll
  src/components/app/home/Cards/Cards.tsx
Labels: enhancement, hacktoberfest-accepted

#181 feat: 180 donation page
  .env.example
  package-lock.json
  package.json
  src/components/Donate/index.tsx
  src/components/shared/Navbar.tsx
  src/pages/app/help.astro
  src/pages/bn/support.astro
  src/pages/bn/team.astro
  src/pages/support.astro
  src/pages/team.astro
Labels: enhancement
