Repository Pujo-Atlas-Kolkata/PujoAtlasKol-Web, pull requests merged in 2024-09, with the labels that each got.

#36 feat: update footer component
  src/components/shared/Footer.astro
  src/icons/discord/index.tsx
  src/icons/index.tsx
  src/icons/reddit/index.tsx
  src/pages/404.astro
  src/pages/index.astro
Labels: enhancement

#38 fix: #15 made view transitions
  src/layouts/Layout.astro
Labels: enhancement

#40 feat(i18n): Setup "bn" Folder Structure Mirroring the Root "en" Page(s)
  astro.config.mjs
  src/components/shared/Navbar.tsx
  src/libs/utils.ts
  src/pages/bn/index.astro
Labels: enhancement

#42 chore: added socials link to constants
  src/components/shared/Footer.astro
  src/components/shared/Navbar.tsx
  src/constants/index.ts
  src/constants/socials.ts
Labels: enhancement

#45 feat: netlify cache test
  netlify.toml
  src/layouts/Layout.astro
  src/pages/index.astro
Labels: bug

#46 feat: add Noto Sans (body) & Alkatra (heading) as fonts for Bengali pages
  netlify.toml
  package-lock.json
  package.json
  src/layouts/Layout.astro
  src/pages/bn/index.astro
  src/pages/index.astro
  tailwind.config.js
Labels: enhancement

#49 feat: add google analytics & partytown
  astro.config.mjs
  package-lock.json
  package.json
  src/layouts/Layout.astro
Labels: enhancement

#47 feat: Sliding Gallery Carousel
  netlify.toml
  package-lock.json
  package.json
  public/idols/1.webp
  public/idols/2.webp
  public/idols/3.webp
  public/idols/4.webp
  public/idols/5.webp
  public/idols/6.webp
  public/idols/7.webp
  public/idols/8.webp
  src/components/Carousel/buttons.tsx
  src/components/Carousel/index.tsx
  src/icons/github/index.tsx
  src/layouts/Layout.astro
  src/pages/bn/index.astro
  src/pages/index.astro
Labels: enhancement

#57 feat: make `/` and `/404` pages mobile responsive
  .astro/settings.json
  src/components/Carousel/index.tsx
  src/components/shared/Footer.astro
  src/components/shared/Header.astro
  src/components/shared/Navbar.tsx
  src/layouts/Layout.astro
  src/pages/404.astro
  src/pages/bn/index.astro
  src/pages/index.astro
Labels: enhancement

#58 feat: set carousel autplay delay to 3000ms, stop autoplay on mouse enter & restart on mouse exit
  src/components/Carousel/index.tsx
Labels: enhancement

#61 fix: configured github link to open in new tab
  src/components/shared/Navbar.tsx
Labels: bug

#73 feat: make the coming soon capsule fully rounded
  src/pages/bn/index.astro
  src/pages/index.astro
Labels: enhancement

#78 fix: smooth scroll & remove scroll down indicator on mobile screens
  src/layouts/Layout.astro
  src/pages/index.astro
Labels: bug

#76 feat: add content for /bn/ page(s)
  src/pages/bn/index.astro
  src/pages/index.astro
Labels: enhancement

#80 fix: reconfigure Noto Sans Bengali + invert scroll bar thumb & trackbar colors
  src/layouts/Layout.astro
  src/pages/bn/index.astro
  src/pages/index.astro
  tailwind.config.js
Labels: bug

#82 fix: minor UI fixes
  astro.config.mjs
  package-lock.json
  package.json
  src/components/Carousel/index.tsx
  src/components/shared/Footer.astro
  src/components/shared/Header.astro
  src/layouts/Layout.astro
  src/pages/bn/index.astro
  src/pages/index.astro
Labels: bug

#74 feat: add buttons for linking to web app + add "/app", "/app/pandals", "/app/booths" routes
  .env.example
  package-lock.json
  package.json
  public/pandal-map-marker.svg
  src/components/app/map/GoogleMap.tsx
  src/components/app/map/LocationMarker.tsx
  src/components/app/map/UserLocation.tsx
  src/components/app/map/types.ts
  src/components/app/shared/AppHeader.astro
  src/components/app/shared/BottomNav.astro
  src/components/app/shared/SearchBar.astro
  src/constants/location.ts
  src/layouts/LandingPageLayout.astro
  src/layouts/WebAppLayout.astro
  src/pages/404.astro
  src/pages/app/booths.astro
  src/pages/app/index.astro
  src/pages/app/pandals.astro
  src/pages/bn/app/index.astro
  src/pages/bn/index.astro
  src/pages/index.astro
  tailwind.config.js
Labels: enhancement

#91 feat: add functionality to Help page
  src/components/app/shared/BottomNav.astro
  src/pages/app/help.astro
Labels: enhancement

#105 fix(app): "Settings" UI
  src/components/app/shared/AppHeader.astro
  src/components/app/shared/AppHeader.tsx
  src/components/app/shared/BottomNav.astro
  src/components/app/shared/Settings/SettingsFlyout.tsx
  src/components/app/shared/SettingsFlyout.tsx
  src/layouts/WebAppLayout.astro
Labels: enhancement

#106 feat: add "Features" & "Get Started" buttons to /bn/ page
  src/pages/bn/index.astro
Labels: enhancement

#108 feat: add a toggle to switch between "Near me" cards and "Trending Pandals" cards
  .astro/settings.json
  package-lock.json
  src/components/app/shared/Card.tsx
  src/components/app/shared/NearMeCard.astro
  src/components/app/shared/PandalCard.tsx
  src/pages/app/index.astro
Labels: enhancement

#111 fix: settings ui nits + remove Google StreetView
  package-lock.json
  src/components/app/map/GoogleMap.tsx
  src/components/app/shared/SettingsFlyout.tsx
  src/pages/app/pandals.astro
Labels: enhancement

#117 feat: fetch pandal list from BE + fix: & toggle location name & navigation button bug
  .github/pull.yml
  src/components/app/map/ClusterMarker.tsx
  src/components/app/map/GoogleMap.tsx
  src/components/app/map/LocationMarker.tsx
  src/components/app/map/types.ts
  src/constants/location.ts
  src/pages/app/pandals.astro
Labels: bug, enhancement

#113 feat: add "Near Me" card & defaults for "Trending" and "Near Me" Pandal Cards
  src/components/app/home/Cards/Cards.tsx
  src/components/app/home/Cards/PandalCard.tsx
  src/components/app/map/GoogleMap.tsx
  src/components/app/map/types.ts
  src/components/app/shared/Card.tsx
  src/components/app/shared/PandalCard.tsx
  src/components/app/shared/SettingsFlyout.tsx
  src/constants/location.ts
  src/layouts/WebAppLayout.astro
  src/libs/utils.ts
  src/pages/app/index.astro
  src/pages/app/pandals.astro
Labels: enhancement

#118 feat: plug-in api for Trending Pandals
  src/components/app/home/Cards/Cards.tsx
  src/components/app/home/Cards/PandalCard.tsx
  src/constants/location.ts
  src/layouts/WebAppLayout.astro
Labels: enhancement

#120 feat: 83 search bar [updated]
  package-lock.json
  package.json
  src/components/app/home/Cards/Cards.tsx
  src/components/app/map/ClusterMarker.tsx
  src/components/app/map/GoogleMap.tsx
  src/components/app/map/LocationMarker.tsx
  src/components/app/map/types.ts
  src/components/app/shared/Search/SearchBar.astro
  src/components/app/shared/Search/input.tsx
  src/components/app/shared/SearchBar.astro
  src/constants/api.ts
  src/constants/index.ts
  src/constants/location.ts
  src/hooks/index.ts
  src/hooks/location/useLocation.ts
  src/hooks/pandals/useAllPandals.ts
  src/hooks/pandals/useTrendingPandals.ts
  src/hooks/search/useDebounce/index.ts
  src/hooks/search/useSearch/index.ts
  src/layouts/LandingPageLayout.astro
  src/layouts/WebAppLayout.astro
  src/libs/utils.ts
  src/pages/app/help.astro
  src/pages/app/index.astro
  src/pages/app/pandals.astro
  src/stores/active/index.ts
  src/stores/index.ts
  src/stores/pujo/index.ts
  src/stores/search/index.ts
  src/types/api.ts
  src/types/index.ts
  src/types/pujo.ts
Labels: enhancement

#123 feat: "near me" toast + web app header chip + /bn/ landing font fix
  package-lock.json
  package.json
  src/components/app/home/Cards/Cards.tsx
  src/components/app/shared/AppHeader.astro
  src/pages/bn/index.astro
  src/pages/index.astro
Labels: bug, enhancement

#125 feat: replace images in carousel present in landing page with Trending Pandal Cards #114
  package-lock.json
  src/components/Carousel/Cards.tsx
  src/components/Carousel/CarouselCard.tsx
  src/components/Carousel/index.tsx
Labels: enhancement

#133 fix: overflow-x
  src/pages/bn/index.astro
  src/pages/index.astro
Labels: bug

#134 feat: landing page carousel UI tweaks
  src/components/Carousel/Cards.tsx
  src/components/Carousel/index.tsx
  src/pages/index.astro
Labels: enhancement

#127 feat: nearme and trending cards are not clickable
  src/components/app/home/Cards/Cards.tsx
  src/components/app/home/Cards/PandalCard.tsx
  src/components/app/map/GoogleMap.tsx
Labels: enhancement

#135 feat: Home tab UI Tweaks
  src/components/app/home/Cards/PandalCard.tsx
Labels: enhancement

#136 feat: update ranking when user clicks on "Get Directions" & "Show On Map" + change button BG Color
  src/components/app/home/Cards/Cards.tsx
  src/components/app/home/Cards/PandalCard.tsx
Labels: enhancement

#137 feat: when user clicks on any pandal search result - take them to /app/pandals and pan the map on that location marker
  src/components/app/shared/Search/input.tsx
Labels: enhancement

#138 feat: make pandal location name and "navigate" button show up automatically when searched from searchbar or from Home tab pandal cards
  src/components/app/home/Cards/PandalCard.tsx
  src/components/app/map/GoogleMap.tsx
  src/components/app/map/UserLocation.tsx
  src/components/app/shared/Search/input.tsx
Labels: enhancement
